import { ReactNode } from "react";
import { ModalProvider, SWRProvider, AuthProvider } from "@/shared/providers";

import "./global.css";

export const metadata = {
  title: "Welcome to auth",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <SWRProvider>
          <ModalProvider>
            <AuthProvider>
              <main className="app">{children}</main>
            </AuthProvider>
          </ModalProvider>
        </SWRProvider>
      </body>
    </html>
  );
}
